/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pdavila
 */
public class Vista extends javax.swing.JFrame {
        
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelContenedor = new javax.swing.JTabbedPane();
        jPanelPais = new javax.swing.JPanel();
        jScrollPanelPais = new javax.swing.JScrollPane();
        jTablePais = new javax.swing.JTable();
        jLabelCodigoPais = new javax.swing.JLabel();
        jLabelNombrePais = new javax.swing.JLabel();
        jLabelContinentePais = new javax.swing.JLabel();
        jLabelRegionPais = new javax.swing.JLabel();
        jLabelPoblacionPais = new javax.swing.JLabel();
        jLabelCapitalPais = new javax.swing.JLabel();
        jTextFieldCodigoPais = new javax.swing.JTextField();
        jTextFieldNombrePais = new javax.swing.JTextField();
        jTextFieldContinentePais = new javax.swing.JTextField();
        jTextFieldRegionPais = new javax.swing.JTextField();
        jTextFieldPoblacionPais = new javax.swing.JTextField();
        jTextFieldCapitalPais = new javax.swing.JTextField();
        jPanelButtonsPais = new javax.swing.JPanel();
        jButtonInsertarPais = new javax.swing.JButton();
        jButtonModificarPais = new javax.swing.JButton();
        jButtonEliminarPais = new javax.swing.JButton();
        jPanelCiudad = new javax.swing.JPanel();
        jScrollPanelCiudad = new javax.swing.JScrollPane();
        jTableCiudad = new javax.swing.JTable();
        jLabelNombreCiudad = new javax.swing.JLabel();
        jLabelDistritoCiudad = new javax.swing.JLabel();
        jLabelCodigoPaisCiudad = new javax.swing.JLabel();
        jLabelPoblacionCiudad = new javax.swing.JLabel();
        jTextFieldNombreCiudad = new javax.swing.JTextField();
        jTextFieldDistritoCiudad = new javax.swing.JTextField();
        jTextFieldCodigoPaisCiudad = new javax.swing.JTextField();
        jTextFieldPoblacionCiudad = new javax.swing.JTextField();
        jPanelButtonsCiudad = new javax.swing.JPanel();
        jButtonInsertarCiudad = new javax.swing.JButton();
        jButtonModificarCiudad = new javax.swing.JButton();
        jButtonEliminarCiudad = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Continente", "Región", "Población", "Capital"
            }
        ));
        jScrollPanelPais.setViewportView(jTablePais);

        jLabelCodigoPais.setText("Código");

        jLabelNombrePais.setText("Nombre");

        jLabelContinentePais.setText("Continente");

        jLabelRegionPais.setText("Región");

        jLabelPoblacionPais.setText("Población");

        jLabelCapitalPais.setText("Capital");

        jButtonInsertarPais.setText("Insertar");

        jButtonModificarPais.setText("Modificar");

        jButtonEliminarPais.setText("Eliminar");

        javax.swing.GroupLayout jPanelButtonsPaisLayout = new javax.swing.GroupLayout(jPanelButtonsPais);
        jPanelButtonsPais.setLayout(jPanelButtonsPaisLayout);
        jPanelButtonsPaisLayout.setHorizontalGroup(
            jPanelButtonsPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsPaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInsertarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonModificarPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelButtonsPaisLayout.setVerticalGroup(
            jPanelButtonsPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInsertarPais)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarPais)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarPais)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPaisLayout = new javax.swing.GroupLayout(jPanelPais);
        jPanelPais.setLayout(jPanelPaisLayout);
        jPanelPaisLayout.setHorizontalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombrePais)
                            .addComponent(jLabelCodigoPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombrePais, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigoPais))
                        .addGap(111, 111, 111)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelContinentePais)
                            .addComponent(jLabelRegionPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldContinentePais)
                            .addComponent(jTextFieldRegionPais, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPoblacionPais, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCapitalPais, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPoblacionPais)
                            .addComponent(jTextFieldCapitalPais, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addComponent(jScrollPanelPais, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtonsPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPaisLayout.setVerticalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelButtonsPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoPais)
                    .addComponent(jTextFieldCodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContinentePais)
                    .addComponent(jTextFieldContinentePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPoblacionPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoblacionPais))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePais)
                    .addComponent(jTextFieldNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegionPais)
                    .addComponent(jTextFieldRegionPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCapitalPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapitalPais))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPanelContenedor.addTab("PAÍS", jPanelPais);

        jTableCiudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Nombre", "Código de país", "Distrito", "Población"
            }
        ));
        jScrollPanelCiudad.setViewportView(jTableCiudad);

        jLabelNombreCiudad.setText("Nombre");

        jLabelDistritoCiudad.setText("Distrito");

        jLabelCodigoPaisCiudad.setText("Código de país");

        jLabelPoblacionCiudad.setText("Población");

        jButtonInsertarCiudad.setText("Insertar");

        jButtonModificarCiudad.setText("Modificar");

        jButtonEliminarCiudad.setText("Eliminar");

        javax.swing.GroupLayout jPanelButtonsCiudadLayout = new javax.swing.GroupLayout(jPanelButtonsCiudad);
        jPanelButtonsCiudad.setLayout(jPanelButtonsCiudadLayout);
        jPanelButtonsCiudadLayout.setHorizontalGroup(
            jPanelButtonsCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonInsertarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelButtonsCiudadLayout.setVerticalGroup(
            jPanelButtonsCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInsertarCiudad)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarCiudad)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarCiudad)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCiudadLayout = new javax.swing.GroupLayout(jPanelCiudad);
        jPanelCiudad.setLayout(jPanelCiudadLayout);
        jPanelCiudadLayout.setHorizontalGroup(
            jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadLayout.createSequentialGroup()
                .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiudadLayout.createSequentialGroup()
                        .addComponent(jScrollPanelCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelButtonsCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCiudadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreCiudad)
                            .addComponent(jLabelDistritoCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreCiudad)
                            .addComponent(jTextFieldDistritoCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(146, 146, 146)
                        .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodigoPaisCiudad)
                            .addComponent(jLabelPoblacionCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigoPaisCiudad)
                            .addComponent(jTextFieldPoblacionCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCiudadLayout.setVerticalGroup(
            jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadLayout.createSequentialGroup()
                .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPanelCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCiudadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelButtonsCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCiudad)
                    .addComponent(jTextFieldNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoPaisCiudad)
                    .addComponent(jTextFieldCodigoPaisCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistritoCiudad)
                    .addComponent(jTextFieldDistritoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoblacionCiudad)
                    .addComponent(jTextFieldPoblacionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPanelContenedor.addTab("CIUDAD", jPanelCiudad);

        jLabelTitulo.setText("GESTIÓN");

        jButtonSalir.setText("Salir del programa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPanelContenedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    public void borrarCamposCiudad() {
        jTextFieldNombreCiudad.setText("");
        jTextFieldCodigoPaisCiudad.setText("");
        jTextFieldDistritoCiudad.setText("");
        jTextFieldPoblacionCiudad.setText("");
    }
    
    public void borrarCamposPais() {
        jTextFieldCodigoPais.setText("");
        jTextFieldNombrePais.setText("");
        jTextFieldContinentePais.setText("");
        jTextFieldRegionPais.setText("");
        jTextFieldPoblacionPais.setText("");
        jTextFieldCapitalPais.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarCiudad;
    private javax.swing.JButton jButtonEliminarPais;
    private javax.swing.JButton jButtonInsertarCiudad;
    private javax.swing.JButton jButtonInsertarPais;
    private javax.swing.JButton jButtonModificarCiudad;
    private javax.swing.JButton jButtonModificarPais;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelCapitalPais;
    private javax.swing.JLabel jLabelCodigoPais;
    private javax.swing.JLabel jLabelCodigoPaisCiudad;
    private javax.swing.JLabel jLabelContinentePais;
    private javax.swing.JLabel jLabelDistritoCiudad;
    private javax.swing.JLabel jLabelNombreCiudad;
    private javax.swing.JLabel jLabelNombrePais;
    private javax.swing.JLabel jLabelPoblacionCiudad;
    private javax.swing.JLabel jLabelPoblacionPais;
    private javax.swing.JLabel jLabelRegionPais;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelButtonsCiudad;
    private javax.swing.JPanel jPanelButtonsPais;
    private javax.swing.JPanel jPanelCiudad;
    private javax.swing.JPanel jPanelPais;
    private javax.swing.JScrollPane jScrollPanelCiudad;
    private javax.swing.JScrollPane jScrollPanelPais;
    private javax.swing.JTabbedPane jTabbedPanelContenedor;
    private javax.swing.JTable jTableCiudad;
    private javax.swing.JTable jTablePais;
    private javax.swing.JTextField jTextFieldCapitalPais;
    private javax.swing.JTextField jTextFieldCodigoPais;
    private javax.swing.JTextField jTextFieldCodigoPaisCiudad;
    private javax.swing.JTextField jTextFieldContinentePais;
    private javax.swing.JTextField jTextFieldDistritoCiudad;
    private javax.swing.JTextField jTextFieldNombreCiudad;
    private javax.swing.JTextField jTextFieldNombrePais;
    private javax.swing.JTextField jTextFieldPoblacionCiudad;
    private javax.swing.JTextField jTextFieldPoblacionPais;
    private javax.swing.JTextField jTextFieldRegionPais;
    // End of variables declaration//GEN-END:variables

    // GENERAL
    public javax.swing.JLabel getjLabelTitulo() { return jLabelTitulo; }
    public javax.swing.JButton getjButtonSalir() { return jButtonSalir; }
    public javax.swing.JTabbedPane getjTabbedPanelContenedor() { return jTabbedPanelContenedor; }
    
    
    // PAIS
    public javax.swing.JPanel getjPanelButtonsPais() { return jPanelButtonsPais; }
    
    public javax.swing.JButton getjButtonInsertarPais() { return jButtonInsertarPais; }
    public javax.swing.JButton getjButtonModificarPais() { return jButtonModificarPais; }
    public javax.swing.JButton getjButtonEliminarPais() { return jButtonEliminarPais; }
    
    public javax.swing.JTextField getjTextFieldCodigoPais() { return jTextFieldCodigoPais; }
    public javax.swing.JTextField getjTextFieldNombrePais() { return jTextFieldNombrePais; }
    public javax.swing.JTextField getjTextFieldContinentePais() { return jTextFieldContinentePais; }
    public javax.swing.JTextField getjTextFieldRegionPais() { return jTextFieldRegionPais; }
    public javax.swing.JTextField getjTextFieldPoblacionPais() { return jTextFieldPoblacionPais; }
    public javax.swing.JTextField getjTextFieldCapitalPais() { return jTextFieldCapitalPais; }
    
    public javax.swing.JLabel getjLabelCodigoPais() { return jLabelCodigoPais; }
    public javax.swing.JLabel getjLabelNombrePais() { return jLabelNombrePais; }
    public javax.swing.JLabel getjLabelContinentePais() { return jLabelContinentePais; }
    public javax.swing.JLabel getjLabelRegionPais() { return jLabelRegionPais; }
    public javax.swing.JLabel getjLabelPoblacionPais() { return jLabelPoblacionPais; }
    public javax.swing.JLabel getjLabelCapitalPais() { return jLabelCapitalPais; }

    public javax.swing.JPanel getjPanelPais() { return jPanelPais; }
    public javax.swing.JTable getjTablePais() { return jTablePais; }
    public javax.swing.JScrollPane getjScrollPanelPais() { return jScrollPanelPais; }

    
    // CIUDAD
    public javax.swing.JPanel getjPanelButtonsCiudad() { return jPanelButtonsCiudad; }
    
    public javax.swing.JButton getjButtonInsertarCiudad() { return jButtonInsertarCiudad; }
    public javax.swing.JButton getjButtonModificarCiudad() { return jButtonModificarCiudad; }
    public javax.swing.JButton getjButtonEliminarCiudad() { return jButtonEliminarCiudad; }
    
    public javax.swing.JTextField getjTextFieldNombreCiudad() { return jTextFieldNombreCiudad; }
    public javax.swing.JTextField getjTextFieldCodigoPaisCiudad() { return jTextFieldCodigoPaisCiudad; }
    public javax.swing.JTextField getjTextFieldDistritoCiudad() { return jTextFieldDistritoCiudad; }
    public javax.swing.JTextField getjTextFieldPoblacionCiudad() { return jTextFieldPoblacionCiudad; }

    public javax.swing.JLabel getjLabelNombreCiudad() { return jLabelNombreCiudad; }
    public javax.swing.JLabel getjLabelCodigoPaisCiudad() { return jLabelCodigoPaisCiudad; }
    public javax.swing.JLabel getjLabelDistritoCiudad() { return jLabelDistritoCiudad; }
    public javax.swing.JLabel getjLabelPoblacionCiudad() { return jLabelPoblacionCiudad; }
    
    public javax.swing.JPanel getjPanelCiudad() { return jPanelCiudad; }
    public javax.swing.JTable getjTableCiudad() { return jTableCiudad; }
    public javax.swing.JScrollPane getjScrollPanelCiudad() { return jScrollPanelCiudad; }

}
